-- =============================================================================
-- QUT Professional Services CRM — Database Schema
-- Target: MySQL 8.0+ (8.4 LTS)
-- Conventions:
--   * UUID primary keys as CHAR(36), generated by the application (C# Guid.NewGuid())
--   * DATETIME(6) for all time fields, stored in UTC + timezone-aware in the app layer
--   * Soft deletes via `deleted_at` (NULL = live record)
--   * Audit columns: created_at, updated_at, created_by, updated_by
--   * FULLTEXT indexes for fuzzy text search on hot paths (no WHERE deleted_at IS NULL in MySQL)
-- =============================================================================

-- MySQL has no extension system. UUID generation happens in application - To team
-- (C# Guid.NewGuid()); FULLTEXT indexing is built into InnoDB.

-- Use utf8mb4 throughout so emoji and the full Unicode range work correctly.
-- utf8mb4_0900_ai_ci is MySQL 8's current default collation, which is case-insensitive and accent-insensitive. 
-- It's a good general-purpose choice for most text fields, including names and free-text descriptions. 
-- If we had specific requirements for case-sensitive or binary comparisons, we could choose different collations on a per-column basis.
-- For now, we'll rely on the default utf8mb4_0900_ai_ci collation for all text fields, as it provides a good balance of usability and 
-- correctness for names, titles, and free-text fields.
-- collation — the right default for names, titles, and free-text fields.

-- =============================================================================
-- 1. LOOKUPS / RBAC
-- =============================================================================

CREATE TABLE roles (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(50) UNIQUE NOT NULL,
    description     TEXT,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO roles (name, description) VALUES
    ('admin',            'Full access. Approves submissions, manages users.'),
    ('course_organiser', 'PS staff. Manages partners, projects, events.'),
    ('industry_partner', 'External user. Registers org and submits project EOIs.');

CREATE TABLE permissions (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    resource        VARCHAR(50)  NOT NULL,   -- e.g. 'organisations', 'projects'
    action          VARCHAR(50)  NOT NULL,   -- e.g. 'create','read','update','delete','approve'
    description     TEXT,
    UNIQUE (resource, action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE role_permissions (
    role_id         INT NOT NULL,
    permission_id   INT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id)   REFERENCES roles(id)    ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE faculties (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(255) UNIQUE NOT NULL,
    code            VARCHAR(50)  UNIQUE,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO faculties (name, code) VALUES
    ('Faculty of Science',                    'SCI'),
    ('Faculty of Engineering',                'ENG'),
    ('Faculty of Business and Law',           'BUS'),
    ('Faculty of Health',                     'HLTH'),
    ('Faculty of Creative Industries',        'CI'),
    ('Faculty of Information Technology',     'IT');

CREATE TABLE industries (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(100) UNIQUE NOT NULL,
    description     TEXT,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO industries (name) VALUES
    ('IT / Software'),
    ('Finance / Banking'),
    ('Health / Medical'),
    ('Government'),
    ('Education'),
    ('Retail / SME'),
    ('Manufacturing'),
    ('Energy / Utilities'),
    ('Telecommunications'),
    ('Other');


-- =============================================================================
-- 2. USERS
--   Note: organisation_id FK is added AFTER organisations is created (circular).
-- =============================================================================

CREATE TABLE users (
    id                  CHAR(36) PRIMARY KEY,
    email               VARCHAR(255) UNIQUE NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,           -- password hash (see AuthService.HashPassword)
    full_name           VARCHAR(255) NOT NULL,
    role_id             INT  NOT NULL,
    faculty_id          INT,                             -- nullable; for course_organisers
    organisation_id     CHAR(36),                        -- for industry_partner users; added via Alter Table (Users) Constraint at bottom of section 3
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at   DATETIME(6),
    last_login_at       DATETIME(6),
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by          CHAR(36),
    updated_by          CHAR(36),
    deleted_at          DATETIME(6),
    FOREIGN KEY (role_id)    REFERENCES roles(id),
    FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_users_role          ON users (role_id);
CREATE INDEX idx_users_faculty       ON users (faculty_id);
CREATE INDEX idx_users_organisation  ON users (organisation_id);


-- =============================================================================
-- 3. ORGANISATIONS (Industry Partners)
-- =============================================================================

CREATE TABLE organisations (
    id                    CHAR(36) PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    legal_name            VARCHAR(255),
    industry_id           INT,
    website               VARCHAR(255),
    domain                VARCHAR(255),
    phone                 VARCHAR(50),
    email                 VARCHAR(255),
    address_line1         VARCHAR(255),
    address_line2         VARCHAR(255),
    city                  VARCHAR(100),
    state                 VARCHAR(100),
    postcode              VARCHAR(20),
    country               VARCHAR(100) DEFAULT 'Australia',
    notes                 TEXT,

    partnership_status    VARCHAR(20) NOT NULL DEFAULT 'prospect',
    submission_status     VARCHAR(20) NOT NULL DEFAULT 'approved',
    submitted_by          CHAR(36),
    reviewed_by           CHAR(36),
    reviewed_at           DATETIME(6),
    review_notes          TEXT,

    created_at            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by            CHAR(36),
    updated_by            CHAR(36),
    deleted_at            DATETIME(6),

    CONSTRAINT chk_org_partnership_status
        CHECK (partnership_status IN ('prospect','active','completed','inactive')),
    CONSTRAINT chk_org_submission_status
        CHECK (submission_status IN ('pending','approved','rejected','archived')),

    FOREIGN KEY (industry_id)  REFERENCES industries(id),
    FOREIGN KEY (submitted_by) REFERENCES users(id),
    FOREIGN KEY (reviewed_by)  REFERENCES users(id),
    FOREIGN KEY (created_by)   REFERENCES users(id),
    FOREIGN KEY (updated_by)   REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_org_name               ON organisations (name);
CREATE INDEX idx_org_industry           ON organisations (industry_id);
CREATE INDEX idx_org_partnership_status ON organisations (partnership_status);
CREATE INDEX idx_org_submission_status  ON organisations (submission_status);
CREATE FULLTEXT INDEX idx_org_name_ft   ON organisations (name);

ALTER TABLE users
    ADD CONSTRAINT fk_users_organisation
    FOREIGN KEY (organisation_id) REFERENCES organisations(id);


-- =============================================================================
-- 4. CONTACTS  (multiple per organisation)
-- =============================================================================

CREATE TABLE contacts (
    id                CHAR(36) PRIMARY KEY,
    organisation_id   CHAR(36) NOT NULL,
    first_name        VARCHAR(100) NOT NULL,
    last_name         VARCHAR(100) NOT NULL,
    job_title         VARCHAR(255),
    email             VARCHAR(255),
    phone             VARCHAR(50),
    is_primary        BOOLEAN NOT NULL DEFAULT FALSE,
    notes             TEXT,
    created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by        CHAR(36),
    updated_by        CHAR(36),
    deleted_at        DATETIME(6),

    FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    FOREIGN KEY (created_by)      REFERENCES users(id),
    FOREIGN KEY (updated_by)      REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_contacts_org   ON contacts (organisation_id);
CREATE INDEX idx_contacts_email ON contacts (email);


-- =============================================================================
-- 5. PROJECTS  (one organisation per project — see schema_design.md re: CO-5)
-- =============================================================================

CREATE TABLE projects (
    id                CHAR(36) PRIMARY KEY,
    title             VARCHAR(500) NOT NULL,
    description       TEXT,
    organisation_id   CHAR(36) NOT NULL,
    faculty_id        INT,

    project_type      VARCHAR(20) NOT NULL,
    semester          VARCHAR(10) NOT NULL,
    year              INT NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'ongoing',

    start_date        DATE,
    end_date          DATE,
    notes             TEXT,

    created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by        CHAR(36),
    updated_by        CHAR(36),
    deleted_at        DATETIME(6),

    CONSTRAINT chk_projects_type     CHECK (project_type IN ('capstone','undergrad','postgrad')),
    CONSTRAINT chk_projects_semester CHECK (semester IN ('S1','S2','SS')),
    CONSTRAINT chk_projects_year     CHECK (year BETWEEN 2019 AND 2100),
    CONSTRAINT chk_projects_status   CHECK (status IN ('proposed','ongoing','completed','cancelled')),

    FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    FOREIGN KEY (faculty_id)      REFERENCES faculties(id),
    FOREIGN KEY (created_by)      REFERENCES users(id),
    FOREIGN KEY (updated_by)      REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_projects_org      ON projects (organisation_id);
CREATE INDEX idx_projects_faculty  ON projects (faculty_id);
CREATE INDEX idx_projects_intake   ON projects (year, semester);
CREATE INDEX idx_projects_type     ON projects (project_type);
CREATE INDEX idx_projects_status   ON projects (status);
CREATE FULLTEXT INDEX idx_projects_title_ft ON projects (title);


-- =============================================================================
-- 6. PROJECT APPLICATIONS  (Industry partner EOIs — IP-2, AD-2)
-- =============================================================================

CREATE TABLE project_applications (
    id                          CHAR(36) PRIMARY KEY,
    organisation_id             CHAR(36) NOT NULL,
    contact_id                  CHAR(36),

    proposed_title              VARCHAR(500) NOT NULL,
    proposed_description        TEXT,
    proposed_project_type       VARCHAR(20),
    proposed_semester           VARCHAR(10),
    proposed_year               INT,
    proposed_faculty_id         INT,

    application_status          VARCHAR(20) NOT NULL DEFAULT 'pending',

    submitted_by                CHAR(36),
    submitted_at                DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_by                 CHAR(36),
    reviewed_at                 DATETIME(6),
    review_notes                TEXT,

    resulting_project_id        CHAR(36),

    created_at                  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by                  CHAR(36),
    updated_by                  CHAR(36),
    deleted_at                  DATETIME(6),

    CONSTRAINT chk_apps_type     CHECK (proposed_project_type IN ('capstone','undergrad','postgrad')),
    CONSTRAINT chk_apps_semester CHECK (proposed_semester IN ('S1','S2','SS')),
    CONSTRAINT chk_apps_status   CHECK (application_status IN ('pending','approved','rejected','archived')),

    FOREIGN KEY (organisation_id)     REFERENCES organisations(id),
    FOREIGN KEY (contact_id)          REFERENCES contacts(id),
    FOREIGN KEY (proposed_faculty_id) REFERENCES faculties(id),
    FOREIGN KEY (submitted_by)        REFERENCES users(id),
    FOREIGN KEY (reviewed_by)         REFERENCES users(id),
    FOREIGN KEY (resulting_project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by)          REFERENCES users(id),
    FOREIGN KEY (updated_by)          REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_apps_org    ON project_applications (organisation_id);
CREATE INDEX idx_apps_status ON project_applications (application_status);
CREATE INDEX idx_apps_intake ON project_applications (proposed_year, proposed_semester);


-- =============================================================================
-- 7. EVENTS + ATTENDANCE  (organisation-level; contact-level deferred)
-- =============================================================================

CREATE TABLE events (
    id                CHAR(36) PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    event_type        VARCHAR(50),
    event_date        DATE NOT NULL,
    location          VARCHAR(255),
    faculty_id        INT,
    notes             TEXT,
    created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by        CHAR(36),
    updated_by        CHAR(36),
    deleted_at        DATETIME(6),

    FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_events_date    ON events (event_date);
CREATE INDEX idx_events_faculty ON events (faculty_id);
CREATE INDEX idx_events_type    ON events (event_type);

CREATE TABLE event_attendances (
    id                CHAR(36) PRIMARY KEY,
    event_id          CHAR(36) NOT NULL,
    organisation_id   CHAR(36) NOT NULL,
    notes             TEXT,
    created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by        CHAR(36),
    updated_by        CHAR(36),
    deleted_at        DATETIME(6),

    FOREIGN KEY (event_id)        REFERENCES events(id),
    FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    FOREIGN KEY (created_by)      REFERENCES users(id),
    FOREIGN KEY (updated_by)      REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX idx_attendance_unique ON event_attendances (event_id, organisation_id);


-- =============================================================================
-- 8. SAVED FILTERS  (user-owned search presets)
-- =============================================================================

CREATE TABLE saved_filters (
    id                CHAR(36) PRIMARY KEY,
    user_id           CHAR(36) NOT NULL,
    entity            VARCHAR(100) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    filters           JSON NOT NULL,
    created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_saved_filters_user_entity ON saved_filters (user_id, entity);


-- =============================================================================
-- 9. AUDIT LOG
-- =============================================================================

CREATE TABLE audit_log (
    id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    table_name    VARCHAR(100) NOT NULL,
    record_id     CHAR(36) NOT NULL,
    action        VARCHAR(20)  NOT NULL,
    changed_by    CHAR(36),
    changed_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    old_values    JSON,
    new_values    JSON,
    ip_address    VARCHAR(45),
    user_agent    TEXT,

    CONSTRAINT chk_audit_action CHECK (action IN ('INSERT','UPDATE','DELETE','SOFT_DELETE','RESTORE')),
    FOREIGN KEY (changed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_audit_record  ON audit_log (table_name, record_id);
CREATE INDEX idx_audit_changed ON audit_log (changed_at);
CREATE INDEX idx_audit_user    ON audit_log (changed_by);


-- =============================================================================
-- 10. TRIGGERS — auto-update updated_at on every row update
-- =============================================================================

-- The Postgres version of this schema used a trigger function (set_updated_at)
-- to auto-update the `updated_at` column on every row update. In MySQL this is
-- handled natively by the `ON UPDATE CURRENT_TIMESTAMP(6)` clause on each
-- `updated_at` column, so no triggers are required.


-- =============================================================================
-- 11. ANALYTICS VIEWS
-- =============================================================================

-- Per-organisation rollup: total projects, first/last engagement, events attended.
CREATE OR REPLACE VIEW v_organisation_stats AS
SELECT
    o.id,
    o.name,
    o.industry_id,
    i.name                              AS industry_name,
    o.partnership_status,
    COUNT(DISTINCT p.id)                AS total_projects,
    MIN(STR_TO_DATE(CONCAT(p.year, '-',
        CASE p.semester WHEN 'S1' THEN '02' WHEN 'S2' THEN '07' ELSE '11' END,
        '-01'), '%Y-%m-%d'))            AS first_project_date,
    MAX(STR_TO_DATE(CONCAT(p.year, '-',
        CASE p.semester WHEN 'S1' THEN '02' WHEN 'S2' THEN '07' ELSE '11' END,
        '-01'), '%Y-%m-%d'))            AS last_project_date,
    COUNT(DISTINCT ea.event_id)         AS events_attended
FROM organisations o
LEFT JOIN industries        i  ON i.id = o.industry_id
LEFT JOIN projects          p  ON p.organisation_id = o.id  AND p.deleted_at IS NULL
LEFT JOIN event_attendances ea ON ea.organisation_id = o.id AND ea.deleted_at IS NULL
WHERE o.deleted_at IS NULL
GROUP BY o.id, o.name, o.industry_id, i.name, o.partnership_status;

-- Per-intake rollup: total projects, unique partners, new vs returning.
-- Intake order: S1 < SS < S2 within a year, encoded as a sortable integer.
CREATE OR REPLACE VIEW v_intake_summary AS
WITH semester_order AS (
    SELECT 'S1' AS semester, 1 AS sem_ord
    UNION ALL SELECT 'SS', 2
    UNION ALL SELECT 'S2', 3
),
partner_first AS (
    SELECT p.organisation_id,
           MIN(p.year * 10 + s.sem_ord) AS first_intake_key
    FROM projects p
    JOIN semester_order s ON s.semester = p.semester
    WHERE p.deleted_at IS NULL
    GROUP BY p.organisation_id
),
projects_keyed AS (
    SELECT p.id, p.organisation_id, p.year, p.semester,
           p.year * 10 + s.sem_ord AS intake_key
    FROM projects p
    JOIN semester_order s ON s.semester = p.semester
    WHERE p.deleted_at IS NULL
)
SELECT
    pk.year,
    pk.semester,
    COUNT(*)                                                                  AS total_projects,
    COUNT(DISTINCT pk.organisation_id)                                        AS unique_partners,
    COUNT(DISTINCT CASE WHEN pf.first_intake_key  = pk.intake_key
                        THEN pk.organisation_id END)                          AS new_partners,
    COUNT(DISTINCT CASE WHEN pf.first_intake_key <> pk.intake_key
                        THEN pk.organisation_id END)                          AS returning_partners
FROM projects_keyed pk
LEFT JOIN partner_first pf ON pf.organisation_id = pk.organisation_id
GROUP BY pk.year, pk.semester
ORDER BY pk.year DESC;

-- Most active partners over the last 3 years.
CREATE OR REPLACE VIEW v_most_active_partners_3yr AS
SELECT
    o.id,
    o.name,
    i.name        AS industry_name,
    COUNT(p.id)   AS project_count
FROM organisations o
JOIN projects p        ON p.organisation_id = o.id AND p.deleted_at IS NULL
LEFT JOIN industries i ON i.id = o.industry_id
WHERE o.deleted_at IS NULL
  AND p.year >= EXTRACT(YEAR FROM CURRENT_DATE) - 3
GROUP BY o.id, o.name, i.name
ORDER BY project_count DESC;